### PR TITLE
embed block for youtube video

### PR DESCRIPTION
**Pull request by pardeepgera23**
Test URLs:
- Before: https://main--aldevron--hlxsites.hlx.page/
- After: https://feature-embed-block--aldevron--hlxsites.hlx.page/test/embed-video

### CODE REVIEW

**Review by davenichols-DHLS — CHANGES_REQUESTED** [review]
Looks good, but the page speed score is very poor.  Are we reviewing that per PR like Adobe are doing?

**Review by teshukatepalli1 — APPROVED** [review]

**Comment by teshukatepalli1** [comment]
> Looks good, but the page speed score is very poor. Are we reviewing that per PR like Adobe are doing?



> Looks good, but the page speed score is very poor. Are we reviewing that per PR like Adobe are doing?

**Comment by teshukatepalli1** [comment]
Code looks good to me

**Review by dkuntze — CHANGES_REQUESTED** [review]
you should not be using jquery at all.

**Comment by dkuntze** [comment]
need to add a URL that has an actual embed on it - changing it to page that doesn't have a the block is just obfuscation.

**Comment by pardeepgera23** [comment]
> need to add a URL that has an actual embed on it - changing it to page that doesn't have a the block is just obfuscation.

Hi Darin - we are using OOTB Embed block here from the block collection without any customisation for showing youtube video. [https://www.hlx.live/developer/block-collection/embed]

**Comment by davenichols-DHLS** [comment]
> need to add a URL that has an actual embed on it - changing it to page that doesn't have a the block is just obfuscation.

Hi @dkuntze , not sure if this was updated since your comment, but I can see the youtube video running on the page in the tests and in the PR:  https://feature-embed-block--aldevron--hlxsites.hlx.page/test/embed-video

**Comment by pardeepgera23** [comment]
Closing this PR and moving the embed block changes to a separate clean branch

**Pull request closed without merging**
