### PR TITLE
bug fix and removed unwanted code for image slider

### LINKED ISSUE #114: Create block for image thumbnail slider
**Summary**

Create a block for the image thumbnail slider for showing gallery.
Example link from current website: 
https://www.aldevron.com/campus

### PR DESCRIPTION
**Pull request by RAJSEKHARMANUBALLA**
Fix #114 

Test URLs:
- Before: https://main--aldevron--hlxsites.hlx.page
- After: https://feature-imageslider--aldevron--hlxsites.hlx.page/test/imageslider

### CODE REVIEW

**Review by dkuntze — CHANGES_REQUESTED** [review]
why not just remove the code vs commenting it out?

**Comment by RAJSEKHARMANUBALLA** [comment]
> why not just remove the code vs commenting it out?

Removed the commented code and added changes for bug #135

**Review by davenichols-DHLS — APPROVED** [review]
Thank you for making the optimisations.  Approved.

**Comment by davenichols-DHLS** [comment]
@dkuntze  - thank you for the review.  This has now been amended, can you please review again?  Thanks.

**Review by davenichols-DHLS — APPROVED** [review]
This is now looking good, the comments have been deleted where needed.

**Pull request merged**
