### PR TITLE
Feature/columnimages

### LINKED ISSUE #70: Create Image slider block
Description:

Authoring Guide:

### PR DESCRIPTION
**Pull request by RAJSEKHARMANUBALLA**
Fix #70 

Test URLs:
- Before: https://main--aldevron--hlxsites.hlx.page/
- After: https://feature-columnimages--aldevron--hlxsites.hlx.page/test/columnimages

Issue # https://github.com/hlxsites/aldevron/issues/70

### CODE REVIEW

**Review by davenichols-DHLS — APPROVED** [review]
Looks good to me.  @dkuntze  - are you happy if we merge?

**Review by davenichols-DHLS — CHANGES_REQUESTED** [review]
The page speed score is low due to CLS, can we do anything to update this?

**Comment by dkuntze** [comment]
> Looks good to me. @dkuntze - are you happy if we merge?

not until the CLS issues are fixed.

**Review by dkuntze — CHANGES_REQUESTED** [review]
fix CLS

**Comment by pardeepgera23** [comment]
> fix CLS

@dkuntze - CLS issue fixed

**Review by dkuntze — APPROVED** [review]

**Comment by pardeepgera23** [comment]
> The page speed score is low due to CLS, can we do anything to update this?

@davenichols-DHLS - This has been addressed

**Review by pardeepgera23 — APPROVED** [review]

**Review by davenichols-DHLS — APPROVED** [review]
Now looking good with the CLS and pagespeed.  Thank you, please merge.

**Pull request merged**
