### PR TITLE
footer development is completed with eslint issues

### PR DESCRIPTION
**Pull request by umamenda**
Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Test URLs:
- After: https://feature-footer--aldevron--hlxsites.hlx.page

### CODE REVIEW

**Review by dkuntze — CHANGES_REQUESTED** [review]
The bottom part of the footer has visual difference between the actual site:

image

**Comment by umamenda** [comment]
Hi @dkuntze,
Content issue fixed.  footer black color will come from body css property. please review.
footer

**Comment by pardeepgera23** [comment]
> The bottom part of the footer has visual difference between the actual site:
> 
> image

@dkuntze  - This has been fixed now

**Review by dkuntze — APPROVED** [review]
I think this is good. You can improve the LHS even more by adding labels to links, etc

**Pull request merged**
