### PR TITLE
video banner block

### LINKED ISSUE #91: Create block for Video Banner
**Summary**

Create a block for video banner as per below link:
https://www.aldevron.com/25th-anniversary

### PR DESCRIPTION
**Pull request by pardeepgera23**
Create Video banner block:

Fix #91 

Test URLs:
- Before: https://main--aldevron--hlxsites.hlx.page/
- After: https://feature-video-banner--aldevron--hlxsites.hlx.page/test/videobanner

### CODE REVIEW

**Review by davenichols-DHLS — CHANGES_REQUESTED** [review]
Still averaging over 90 on the Adobe server, meaning about 93 when live.  I guess there are no additional optimisations?  @dkuntze  - should we accept 90 on a page running videos in the background?

**Comment by davenichols-DHLS** [comment]
@pardeepgera23  - can we stop the video loading on mobile to see if that brings up the page speed score?

**Comment by pardeepgera23** [comment]
> @pardeepgera23 - can we stop the video loading on mobile to see if that brings up the page speed score?

@davenichols-DHLS - we have removed the video loading on mobile view and used background image in mobile view. Slight performance gain achieved using the same.

**Review by davenichols-DHLS — APPROVED** [review]
This is good now, at 93 page speed on mobile.

**Pull request merged**
